[tool.poetry]
name = "papas-lamp"
version = "0.1.0"
description = ""
authors = ["Meermiri <miriamvanderhoek@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.9"
cadquery = "^2.4.0"
ocp-vscode = "^2.3.3"
cadquery-ocp = "^7.7.0"
build123d = "^0.5.0"

[tool.poetry.scripts]
papas-lamp = 'papas-lamp:main'

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.lint]
# 1. Enable flake8-bugbear (`B`) rules, in addition to the defaults.
select = ["E4", "E7", "E9", "F", "B"]

# 2. Avoid enforcing line-length violations (`E501`)
ignore = ["F403","F405"]
