[tool.poetry]
name = "build123d-projects"
version = "0.1.0"
description = "random cad projects"
authors = ["Reinout Holtrup <reinout91@gmail.com>"]
license = "gpl3"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.12"
cadquery = "^2.4.0"
build123d = { git = "https://github.com/gumyr/build123d.git", branch = "dev" }
ocp-vscode = "^2.3.3"

[tool.poetry.group.dev.dependencies]
cq-warehouse = {git = "https://github.com/gumyr/cq_warehouse.git"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.lint]
# 1. Enable flake8-bugbear (`B`) rules, in addition to the defaults.
select = ["E4", "E7", "E9", "F", "B"]

# 2. Avoid enforcing line-length violations (`E501`)
ignore = ["F403","F405"]