[tool.poetry]
name = "papas-lamp"
version = "0.1.0"
description = ""
authors = ["Meermiri <miriamvanderhoek@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
cadquery = "^2.4.0"
ocp-vscode = "^2.3.3"
cadquery-ocp = "^7.7.0"
build123d = "^0.5.0"

[tool.poetry.scripts]
papas-lamp = 'papas-lamp:main'

[build-system]
requires = [ "setuptools" ]
build-backend = "setuptools.build_meta"
